#Screen and displaying - all 
SCREEN_RESOLUTION: [1300, 700]
EMPTY_SCREEN_TIME: 120
FIXATION_TIME: 120
MASKED_PRESENTATION_TIME: 120
TARGET_FIXATION_TIME: 120
FULL_STIM_TIME: 120

#Experiment
REACTION_KEYS: [a, l] #should be two values
NO_BLOCKS: 2

